import { DriveFolder, Track } from '../types';

export const INITIAL_DRIVE_FOLDERS: DriveFolder[] = [
  {
    id: 'folder-synthwave',
    name: 'Synthwave Night Drive',
    trackCount: 4,
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=500&auto=format&fit=crop&q=80',
    color: '#8b5cf6',
    description: 'Neon retro synthwave and cyberpunk electronic beats from Google Drive.',
  },
  {
    id: 'folder-lofi',
    name: 'Lofi Study & Chill Beats',
    trackCount: 4,
    coverUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=500&auto=format&fit=crop&q=80',
    color: '#10b981',
    description: 'Mellow lofi beats, coffee shop vibes, and deep concentration music.',
  },
  {
    id: 'folder-ambient',
    name: 'Deep Focus & Ambient Space',
    trackCount: 4,
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80',
    color: '#3b82f6',
    description: 'Ethereal ambient soundscapes and atmospheric meditative waves.',
  },
  {
    id: 'folder-acoustic',
    name: 'Acoustic Sunset Sessions',
    trackCount: 3,
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80',
    color: '#f59e0b',
    description: 'Warm fingerstyle acoustic guitar melodies and soulful organic rhythms.',
  },
];

export const INITIAL_TRACKS: Track[] = [
  {
    id: 'track-neon-horizon',
    title: 'Neon Horizon',
    artist: 'Kavinsky Wave',
    album: 'Outrun Odyssey',
    duration: 198,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverending_Story.mp3',
    source: 'demo',
    driveFolderId: 'folder-synthwave',
    folderName: 'Synthwave Night Drive',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=500&auto=format&fit=crop&q=80',
    genre: 'Synthwave',
    year: 2024,
    size: 4720000,
    addedAt: Date.now() - 3600000 * 24 * 3,
  },
  {
    id: 'track-cyber-express',
    title: 'Cyber Highway 2088',
    artist: 'Vector Pulse',
    album: 'Tokyo Driftlines',
    duration: 165,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-_Be_There.mp3',
    source: 'demo',
    driveFolderId: 'folder-synthwave',
    folderName: 'Synthwave Night Drive',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=80',
    genre: 'Darksynth',
    year: 2024,
    size: 3950000,
    addedAt: Date.now() - 3600000 * 24 * 2,
  },
  {
    id: 'track-midnight-city',
    title: 'Midnight Grid Runner',
    artist: 'Digital Dreamscape',
    album: 'Outrun Odyssey',
    duration: 215,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg',
    source: 'demo',
    driveFolderId: 'folder-synthwave',
    folderName: 'Synthwave Night Drive',
    coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=80',
    genre: 'Synthwave',
    year: 2024,
    size: 5120000,
    addedAt: Date.now() - 3600000 * 24 * 1,
  },
  {
    id: 'track-analog-glitch',
    title: 'Retro Chrome Memory',
    artist: 'Hyperion Echo',
    album: 'Future Nostalgia',
    duration: 182,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/pyman_assets/intromusic.ogg',
    source: 'demo',
    driveFolderId: 'folder-synthwave',
    folderName: 'Synthwave Night Drive',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80',
    genre: 'Chiptune',
    year: 2023,
    size: 3400000,
    addedAt: Date.now() - 3600000 * 12,
  },
  {
    id: 'track-rainy-coffee',
    title: 'Rainy Afternoon Coffee',
    artist: 'Sleepy Panda',
    album: 'Tokyo Rainy Days',
    duration: 154,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverending_Story.mp3',
    source: 'demo',
    driveFolderId: 'folder-lofi',
    folderName: 'Lofi Study & Chill Beats',
    coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=500&auto=format&fit=crop&q=80',
    genre: 'Lofi Hip Hop',
    year: 2024,
    size: 3600000,
    addedAt: Date.now() - 3600000 * 48,
  },
  {
    id: 'track-floating-clouds',
    title: 'Floating Clouds in Shinjuku',
    artist: 'Nujabes Spirit',
    album: 'Autumn Breeze',
    duration: 190,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-_Be_There.mp3',
    source: 'demo',
    driveFolderId: 'folder-lofi',
    folderName: 'Lofi Study & Chill Beats',
    coverUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=500&auto=format&fit=crop&q=80',
    genre: 'Lofi Chill',
    year: 2024,
    size: 4500000,
    addedAt: Date.now() - 3600000 * 36,
  },
  {
    id: 'track-study-session',
    title: 'Midnight Chemistry Homework',
    artist: 'Lo-Fi Girl Records',
    album: 'Desk Lights',
    duration: 172,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg',
    source: 'demo',
    driveFolderId: 'folder-lofi',
    folderName: 'Lofi Study & Chill Beats',
    coverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=500&auto=format&fit=crop&q=80',
    genre: 'Lofi Beats',
    year: 2024,
    size: 4100000,
    addedAt: Date.now() - 3600000 * 20,
  },
  {
    id: 'track-soft-vibrations',
    title: 'Warm Matcha Latte',
    artist: 'Bonsai Dreams',
    album: 'Autumn Breeze',
    duration: 145,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/pyman_assets/intromusic.ogg',
    source: 'demo',
    driveFolderId: 'folder-lofi',
    folderName: 'Lofi Study & Chill Beats',
    coverUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=500&auto=format&fit=crop&q=80',
    genre: 'Lofi Chill',
    year: 2024,
    size: 3200000,
    addedAt: Date.now() - 3600000 * 10,
  },
  {
    id: 'track-orbital-decay',
    title: 'Interstellar Nebula Drift',
    artist: 'Cosmic Voyager',
    album: 'Deep Space Journey',
    duration: 245,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg',
    source: 'demo',
    driveFolderId: 'folder-ambient',
    folderName: 'Deep Focus & Ambient Space',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80',
    genre: 'Ambient',
    year: 2023,
    size: 5800000,
    addedAt: Date.now() - 3600000 * 60,
  },
  {
    id: 'track-aurora-borealis',
    title: 'Polar Light Waves',
    artist: 'Nordic Soundscapes',
    album: 'Fjord Reflections',
    duration: 210,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-_Be_There.mp3',
    source: 'demo',
    driveFolderId: 'folder-ambient',
    folderName: 'Deep Focus & Ambient Space',
    coverUrl: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?w=500&auto=format&fit=crop&q=80',
    genre: 'Ambient Drone',
    year: 2024,
    size: 4900000,
    addedAt: Date.now() - 3600000 * 40,
  },
  {
    id: 'track-golden-hour',
    title: 'Golden Hour Memories',
    artist: 'Acoustic Traveler',
    album: 'Wooden Strings',
    duration: 168,
    url: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverending_Story.mp3',
    source: 'demo',
    driveFolderId: 'folder-acoustic',
    folderName: 'Acoustic Sunset Sessions',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80',
    genre: 'Acoustic',
    year: 2024,
    size: 3800000,
    addedAt: Date.now() - 3600000 * 70,
  },
];
